title: Godot Cookbook
author: The University of Alabama Libraries
copyright: "2024"
logo: images/UALIB_logo.png

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

# bibtex_bibfiles:
#   - references.bib

repository:
  url: https://github.com/ualibweb/Godot-Cookbook  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  favicon: images/UALIB_favicon.png
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  colab_url: ""
  binderhub_url: ""
  jupyterhub_url: ""